[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Handle form submissions
[forms]

# 404 redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404